variables:
  DOCKER_IMG: "registry.gitlab.com/offa/plug/ci"

stages:
  - build-docker-images
  - build



# -----------------------------------------
# --- CI Builds
# -----------------------------------------
gcc-7:
  image: ${DOCKER_IMG}/gcc-7:latest
  stage: build
  script:
    - script/ci_build.sh

clang-5:
  image: ${DOCKER_IMG}/clang-5:latest
  stage: build
  script:
    - script/ci_build.sh



# -----------------------------------------
# --- CI Images
# -----------------------------------------
build-ci-gcc-7:
  image: docker:latest
  stage: build-docker-images
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  script:
    - docker build --pull --build-arg COMPILER=gcc-7 -t ${DOCKER_IMG}/gcc-7 .
    - docker push ${DOCKER_IMG}/gcc-7
  only:
    - web
    - trigger
    - /^docker-.*$/

build-ci-clang-5:
  image: docker:latest
  stage: build-docker-images
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  script:
    - docker build --pull --build-arg COMPILER=clang-5 -t ${DOCKER_IMG}/clang-5 .
    - docker push ${DOCKER_IMG}/clang-5
  only:
    - web
    - trigger
    - /^docker-.*$/

