name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc-12
          - gcc-11
          - clang-15
          - clang-14
    container:
      image: "registry.gitlab.com/offa/docker-images/${{ matrix.compiler }}:stable"
    name: "${{ matrix.compiler }}"
    steps:
      - uses: actions/checkout@main
      - name: Setup
        run: script/ci_setup.sh
      - name: Build
        run: script/ci_build.sh -asan -ubsan

  formatting-check:
    name: "formatting"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: DoozyX/clang-format-lint-action@master
      name: "Verify formatting"
      with:
        clangFormatVersion: 14

