name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc-12
          - gcc-11
          - gcc-10
          - clang-14
          - clang-13
          - clang-12
    container:
      image: "registry.gitlab.com/offa/plug/ci/${{ matrix.compiler }}:latest"
    name: "${{ matrix.compiler }}"
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: script/ci_build.sh -asan -ubsan
